version = 0.1
[UAT]
[UAT.deploy]
[UAT.deploy.parameters]
stack_name = "sam-api-sample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s7ts04woxm1l"
s3_prefix = "sam-api-sample"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-api-sample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s7ts04woxm1l"
s3_prefix = "sam-api-sample"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
